{{- if .Values.pdb }}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "feeds-worker.fullname" . }}
spec:
{{ toYaml .Values.pdb | indent 2 -}}
  selector:
    matchLabels:
      {{- include "feeds-worker.selectorLabels" . | nindent 6 }}
{{- end }}
