---
{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "feeds-worker.fullname" . }}
  labels:
    {{- include "feeds-worker.labels" . | nindent 4 }}
type: Opaque
data:
{{- range .Values.secrets }}
  {{ .name }}: {{ .value | b64enc | quote }}
{{- end }}
{{- end }}
