---
# Logging map partially mimics configuration of uber/zap Config structure
# See  https://pkg.go.dev/go.uber.org/zap
logging:
  # Development key puts the logger in development mode, which changes the behavior of DPanicLevel and takes stacktraces more liberally.
  development: true
  # level: info
  level: {{ .Values.config.logging.level }}
  encoding: {{ .Values.config.logging.encoding }}
  # encoding: json
  # encoding: console
  disable_caller: {{ .Values.config.logging.disable_caller }}
  disable_stacktrace: {{ .Values.config.logging.disable_stacktrace }}
  disable_color: {{ .Values.config.logging.disable_color }}
  # output_paths: ["stdout", "/tmp/1.log"]
  output_paths: ["stdout"]
  error_output_paths: ["stderr"]

tracing:
  service_name: "{{ .Values.config.tracing.service_name }}"
  sampler_rate: {{ .Values.config.tracing.sampler_rate }}
  sampler_type: "{{ .Values.config.tracing.sampler_type }}"
  agent_address: "{{ .Values.config.tracing.agent_address }}"
  collector_endpoint: "{{ .Values.config.tracing.collector_endpoint }}"
  log_spans: {{ .Values.config.tracing.log_spans }}

database:
  hostname: {{ .Values.config.database.hostname }}
  port: {{ .Values.config.database.port }}
  name: {{ .Values.config.database.name }}
  username: {{ .Values.config.database.username }}
  password: {{ .Values.config.database.password }}
  sslmode: {{ .Values.config.database.sslmode }}
  min_connections: {{ .Values.config.database.min_connections }}
  max_connections: {{ .Values.config.database.max_connections }}

consume:
  nsqlookup: {{ .Values.config.consume.nsqlookup }}
  topic: {{ .Values.config.consume.topic }}
  channel: {{ .Values.config.consume.channel }}
  # prefetch (in flight) messages should be bigger than workers
  prefetch: {{ .Values.config.consume.prefetch }}
  workers: {{ .Values.config.consume.workers }}
  attempts: {{ .Values.config.consume.attempts }}

publish:
  host: {{ .Values.config.publish.host }}
  topic: {{ .Values.config.publish.topic }}

itemPublish:
  host: {{ .Values.config.itemPublish.host }}
  topic: {{ .Values.config.itemPublish.topic }}