---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tern-sql-migrations.fullname" . }}
  labels:
    {{- include "tern-sql-migrations.labels" . | nindent 4 }}
data:
  tern.conf: |-
{{ tpl (.Files.Get "configs/tern.conf") . |indent 4 }}
