---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic-worker.fullname" . }}
  labels:
    {{- include "generic-worker.labels" . | nindent 4 }}
data:
  config.yaml: |-
{{ .Values.config.content | nindent 4 }}
