---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: items-code
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/tarick/projects/mine/go/naca/items/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: items-code
  namespace: naca
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
