---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic-api.fullname" . }}
  labels:
    {{- include "generic-api.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Values.config.content | nindent 4 }}
