---
{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-api.fullname" . }}
  labels:
    {{- include "generic-api.labels" . | nindent 4 }}
type: Opaque
data:
{{- range .Values.secrets }}
  {{ .name }}: {{ .value | b64enc | quote }}
{{- end }}
{{- end }}
