# These imports of "environments" values are only for rendering in .gotmpl
# use "helmfile --environment test" to filter out env
environments:
  local:
    values:
      - environments/default/values.yaml.gotmpl
      - environments/local/values.yaml.gotmpl
    missingFileHandler: Warn
  production:
    values:
      - environments/default/values.yaml.gotmpl
      - environments/production/values.yaml.gotmpl
    missingFileHandler: Warn
