---
{{ readFile "common.yaml" }}
bases:
  - environments.yaml
---
# Helm release names are not namespaced, name will have `dev` or `prod` prefix
releases:
  - name: postgresql
    labels:
      app_name: "postgresql"
      tier: "naca"
    chart: "bitnami/postgresql"
    version: 10.2.0
    namespace: naca
    missingFileHandler: Warn
    values:
      - environments/default/postgresql/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/roles/postgresql/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/namespaces/naca/postgresql/values.yaml.gotmpl   # Final overrides
  # By default we disable all traffic to postgresql. Here we enable it for other NS/pods.
  - name: postgresql-network-policy
    labels:
      app_name: "postgresql-network-policy"
      tier: "naca"
    chart: "./charts/generic-network-policy"
    namespace: naca
    missingFileHandler: Warn
    needs:
      - naca/postgresql
    values:
      - environments/default/postgresql-network-policy/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/roles/postgresql-network-policy/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/namespaces/naca/postgresql-network-policy/values.yaml.gotmpl   # Final overrides

  - name: nsq
    labels:
      app_name: "nsq"
      tier: "naca"
    chart: "./charts/nsq"
    namespace: naca
    missingFileHandler: Warn
    values:
      - environments/default/nsq/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/roles/nsq/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/namespaces/naca/nsq/values.yaml.gotmpl   # Final overrides
  # By default we disable all traffic to nsq. Here we enable it for other NS/pods.
  - name: nsq-network-policy
    labels:
      app_name: "nsq-network-policy"
      tier: "naca"
    chart: "./charts/generic-network-policy"
    namespace: naca
    missingFileHandler: Warn
    needs:
      - naca/nsq
    values:
      - environments/default/nsq-network-policy/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/roles/nsq-network-policy/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/namespaces/naca/nsq-network-policy/values.yaml.gotmpl   # Final overrides

  - name: rss-feeds-sql-migrations
    labels:
      app_name: "rss-feeds-sql-migrations"
      tier: "naca-rss-feeds"
    chart: "./charts/tern-sql-migrations"
    namespace: naca-rss
    missingFileHandler: Warn
    values:
      - environments/default/rss-feeds-sql-migrations/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/roles/rss-feeds-sql-migrations/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/namespaces/naca/rss-feeds-sql-migrations/values.yaml.gotmpl   # Final overrides
      - image:
          tag: '{{ env "RSS_FEEDS_TAG" | default "undefinedTag" }}'
  - name: rss-feeds-worker
    labels:
      app_name: "rss-feeds-worker"
      tier: "naca-rss-feeds"
    chart: "./charts/generic-worker"
    namespace: naca-rss
    missingFileHandler: Warn
    needs:
      - naca-rss/rss-feeds-sql-migrations
    values:
      - environments/default/rss-feeds-worker/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/roles/rss-feeds-worker/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/namespaces/naca/rss-feeds-worker/values.yaml.gotmpl   # Final overrides
      - image:
          tag: '{{ env "RSS_FEEDS_TAG" | default "undefinedTag" }}'
  - name: rss-feeds-api
    labels:
      app_name: "rss-feeds-api"
      tier: "naca-rss-feeds"
    chart: "./charts/generic-api"
    namespace: naca-rss
    needs:
      - naca-rss/rss-feeds-sql-migrations
    missingFileHandler: Warn
    values:
      - environments/default/rss-feeds-api/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/roles/rss-feeds-api/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/namespaces/naca/rss-feeds-api/values.yaml.gotmpl   # Final overrides
      - image:
          tag: '{{ env "RSS_FEEDS_TAG" | default "undefinedTag" }}'
  - name: rss-refresh-cronjob
    labels:
      app_name: "rss-feeds-refresh-cronjob"
      tier: "naca-rss-feeds"
    chart: "./charts/generic-cronjob"
    namespace: naca-rss
    needs:
      - naca-rss/rss-feeds-api
    missingFileHandler: Warn
    values:
      - environments/default/rss-feeds-refresh-cronjob/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/roles/rss-feeds-refresh-cronjob/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/namespaces/naca/rss-feeds-refresh-cronjob/values.yaml.gotmpl   # Final overrides

  - name: publications-sql-migrations
    labels:
      app_name: "publications-sql-migrations"
      tier: "naca-publications"
    chart: "./charts/tern-sql-migrations"
    namespace: naca-publications
    missingFileHandler: Warn
    values:
      - environments/default/publications-sql-migrations/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/roles/publications-sql-migrations/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/namespaces/naca/publications-sql-migrations/values.yaml.gotmpl   # Final overrides
      - image:
          tag: '{{ env "PUBLICATIONS_TAG" | default "undefinedTag" }}'

  - name: publications-api
    labels:
      app_name: "publications-api"
      tier: "naca-publications"
    chart: "./charts/generic-api"
    namespace: naca-publications
    needs:
      - naca-publications/publications-sql-migrations
    missingFileHandler: Warn
    values:
      - environments/default/publications-api/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/roles/publications-api/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/namespaces/naca/publications-api/values.yaml.gotmpl   # Final overrides
      - image:
          tag: '{{ env "PUBLICATIONS_TAG" | default "undefinedTag" }}'

  - name: items-sql-migrations
    labels:
      app_name: "items-sql-migrations"
      tier: "naca-items"
    chart: "./charts/tern-sql-migrations"
    namespace: naca-items
    missingFileHandler: Warn
    values:
      - environments/default/items-sql-migrations/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/roles/items-sql-migrations/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/namespaces/naca/items-sql-migrations/values.yaml.gotmpl   # Final overrides
      - image:
          tag: '{{ env "ITEMS_TAG" | default "undefinedTag" }}'

  - name: items-worker
    labels:
      app_name: "items-worker"
      tier: "naca-items"
    chart: "./charts/generic-worker"
    namespace: naca-items
    needs:
      - naca-items/items-sql-migrations
    missingFileHandler: Warn
    values:
      - environments/default/items-worker/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/roles/items-worker/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/namespaces/naca/items-worker/values.yaml.gotmpl   # Final overrides
      - image:
          tag: '{{ env "ITEMS_TAG" | default "undefinedTag" }}'
  - name: items-api
    labels:
      app_name: "items-api"
      tier: "naca-items"
    chart: "./charts/generic-api"
    namespace: naca-items
    needs:
      - naca-items/items-sql-migrations
    missingFileHandler: Warn
    values:
      - environments/default/items-api/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/roles/items-api/values.yaml.gotmpl   # Shared env settings
      - environments/{{ .Environment.Name }}/namespaces/naca/items-api/values.yaml.gotmpl   # Final overrides
      - image:
          tag: '{{ env "ITEMS_TAG" | default "undefinedTag" }}'
