---
{{ readFile "common.yaml" }}
bases:
  - clusters.yaml
---
repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: cilium
    url: https://helm.cilium.io/
  - name: kiali
    url: https://kiali.org/helm-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: jaegertracing
    url: https://jaegertracing.github.io/helm-charts

# Helm release names are not namespaced, name will have `dev` or `prod` prefix
releases:
  - name: cilium
    labels:
      app_name: "cilium"
      tier: "cluster"
    chart: "cilium/cilium"
    namespace: cilium
    missingFileHandler: Warn
    version: 1.9.3
    values:
      - clusters/{{ .Environment.Name }}/roles/cilium/values.yaml.gotmpl   # Shared env settings
  - name: local-path-provisiner
    labels:
      app_name: "local-path-provisiner"
      tier: "cluster"
    chart: "./charts/local-path-provisioner"
    namespace: kube-system
    missingFileHandler: Warn
    values:
      - clusters/{{ .Environment.Name }}/roles/local-path-provisioner/values.yaml.gotmpl   # Shared env settings
  - name: metallb
    labels:
      app_name: "metallb"
      tier: "cluster"
    chart: "bitnami/metallb"
    version: 2.0.1
    namespace: metallb
    missingFileHandler: Warn
    values:
      - clusters/{{ .Environment.Name }}/roles/metallb/values.yaml.gotmpl   # Shared env settings

  - name: metrics-server
    labels:
      app_name: "metrics-server"
      tier: "cluster"
    chart: "stable/metrics-server"
    namespace: monitoring
    missingFileHandler: Warn
    values:
      - clusters/{{ .Environment.Name }}/roles/metrics-server/values.yaml.gotmpl   # Shared env settings

  - name: prometheus
    labels:
      app_name: "prometheus"
      tier: "cluster"
    chart: "prometheus-community/prometheus"
    namespace: monitoring
    missingFileHandler: Warn
    values:
      - clusters/{{ .Environment.Name }}/roles/prometheus/values.yaml.gotmpl   # Shared env settings

  - name: grafana
    labels:
      app_name: "grafana"
      tier: "cluster"
    chart: "grafana/grafana"
    version: 6.1.16
    namespace: monitoring
    missingFileHandler: Warn
    values:
      - clusters/{{ .Environment.Name }}/roles/grafana/values.yaml.gotmpl   # Shared env settings

  - name: kiali
    labels:
      app_name: "kiali"
      tier: "cluster"
    chart: "kiali/kiali-server"
    version: 1.28.1
    namespace: monitoring
    missingFileHandler: Warn
    values:
      - clusters/{{ .Environment.Name }}/roles/kiali/values.yaml.gotmpl   # Shared env settings

  - name: jaeger
    labels:
      app_name: "jaeger"
      tier: "cluster"
    chart: "jaegertracing/jaeger"
    version: 0.39.7
    namespace: jaeger
    missingFileHandler: Warn
    values:
      - clusters/{{ .Environment.Name }}/roles/jaeger/values.yaml.gotmpl   # Shared env settings
